apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVTUpIeUFDNTRva2ZWU1A4TG4zM3YzNS90aU5zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXpNRFV4T0RFeU16TXdPVm9YRFRJek1EWXhOekV5TXpNd09Wb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdnMUgwb25XNEdaZ2JKZkxFMGhZVXZQdXZvWU9OYVNxVjQxUgpTdkNFZk9zL29SaTA0MS9BUldTRlA3QWxweGwrWUJuK1NSUzJUeE1RQktSZCtWK0MwTFRnb1hmL2JPcUxSeUwrCnB6WHhBT1MrbTMrTnJ0N2IvM1hrblc4Ri9xQXZVdmp4U2ZxcTNQTnYydDVRS05ZY1ExUG1NTW9hUG9IWnlGMmsKVVM1S2Npc05nVm53NXptWit2RmNLSDgzcVlEUkNpNHgwYXFmQUM2RXJQYm1CNHpwbkZEWk8zUUREcHVaOTI3bAo2QVdZRjBsNm5KTFdKYVFWY2Roam9GN2dZenpJUjI4NVVpZk5LUmRvM3RXSWxZdGtXYjFKamFjOVgyb1dYRE85Ck4rcVdKTjJjaVBrY0FkdWhzcDA5MTNuVEhjZFVaUHVRNGlwYk9JUjFHRW15eG5ocTB3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVcklDN1BDT0dYeE1FTGZVNzFnVlk4REF3UnB3d0h3WURWUjBqQkJnd0ZvQVVySUM3UENPRwpYeE1FTGZVNzFnVlk4REF3UnB3d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFCN0t3WDJtaWNpcWdJTWRseHVmeTFnMnlWT21ZU1IvNld3Z0l0L0JTdDd0alptUHpyM05Vb0E2WFJBNTAKaUNXcjZXZ0F0SG5QYVViVjYwd2R3NTlUWVg0Q1dwK284cFgycnZTMHJGa0hGaWNIVWpFV1lpaGE2UnlSamF1WgpUTm9GT0YvM2U3SnhaYlk3Z2xjMXdDYnE0NTM4UXlGN3Jza3dYLzNEditxL21UaExSN1hWaVlid1lybEpvcndIClpJZy9kcEJvVjU5RU1vZXdva2s2RnNMOGgwZ0J1RmV3dGJiNTdLcm5Pb3ppSEt1M0kvWGJySzVicUFJaFNWTDkKVlY4enlpdThndDFJbnM3ZUQvOFJNVktLVXh1L3I5Y3VmKzBLbjJuOVg0My9hTlhsMExIWXozVHVQWHMrWFFnRwpyTHFyN1ZnaGJjZ3MxeTg0eWdlRlgyTTNadz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]