apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVTVdBRGFkenpaalR3WUppUjZvcWtyNmlmOENFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXpNRFV4T0RFeE1EVTBOVm9YRFRJek1EWXhOekV4TURVME5Wb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXlKZFVEWTRkdVlodllYanV0K0VGOTBUb3NkK29ML3kxS0cxNgo3WmhYUjlWTDVIMDBsWnBxZ0J3WStGNE1tdUIxSEhNdG4zZXFNVDFaWmtIVTBuM1N6Y1pDSFdqSW5VOU51MTNSCjZlQ1NZN0ppK3RoYkM1YjdUV2kyYTRFYUhya0prUC9iVEZWcHJySUxxWTBMU2FGUGtxU1diWnNPRTRmL1k4aVYKTm0vZWk5cFMzNlJvZEl4MkEvUC9Xa0xJUjY3dWtOS0dyTENaN25RWHJrejlPa1dZbjF0Y2s1NnVHTzN4TFduOApwS1Z3ekRPR1R2Z28wcmsvR1R0ckNkSWI3bTdmbnhuWjVpM2wzQVpOd3JYU3JrSGFCQUZneHFNRnJBUkM1SGtkCmdDeUlaNVFFWEw1bnpjbUtOdU01UnUzVE1LUXRZVVJ2TXE4ZlMvQS8xcDB0Y2RFR2F3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVVGZ0R212ME9EbmYvSXBTUmlhbXIzZXVBMGNzd0h3WURWUjBqQkJnd0ZvQVVUZnRHbXYwTwpEbmYvSXBTUmlhbXIzZXVBMGNzd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFEYnE2c0NLc081dkM0Y1FQcEFuNExiTnplV0MwL0R5UlkrMWF3RklSMnBrR2VaQjVzWUk5VXI0TmVBbVQKNmpNYkd2aHBJOHMvTEdKV213Vi9HS1ZqU2tNWHoycE9OaVo3elBFVUJENUhubVJFeGE4SjI3UXJvV21mOEd2MwprRkk1a2lKb2J1T0UxdC9mdk5yd21iL0U2dFVVMXZEb3luMm9ZQWRWSjIraTBmV2I0MnJpRUphRFVjaGlIUUJ5Cm1LSnVCMlZ5VncwUjJiSXBxSjRTV04vTzZ2Q0oydXI2Rld0U1RIT0tSZm5JMkx5S21tOU1qb0RnVTQzM2JseWUKVVg2czVZczR3M005OWRLYUVwSFFDcjlVeVVSS1dWNzh3L2V6b1hCd0FtaW41MmJvTDhScS95bloweit5UXdROQo1emo2UlY4eXpVS1NwWUJEbmdXY3J6WFhBQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]