apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVUGZWZDVKM2VBNGwzbUkxeFc3N21IZm5sMDZZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXpNRFV4T0RFd01qQTFOMW9YRFRJek1EWXhOekV3TWpBMU4xb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXRrckdJQ0NUTVE5RE8wVEYwc2ZlelVTTDc4aW90VTcvY2sxcwpEMnZMVGV1QVF4OE45bDAxYUpNQXBla1JCTEIwMVFjTUthcUR6cjBsOE45eDBOZENNc1hldHJCZkR0NVJvN0lhClcreVY1bmxYQTBaUGVCR3BRZTlqQXRHK25FdEFKWlM5dEM0R0pwMmlyRzgwdGx6dlZyWTdtSlRHZzQ5dHhoL1QKMGMvVUsvYWcxSnNoQ2Z1YTY3Z2Jqb1lTdHh4VTZnN2JHYXVnR0RFc0llL1FmZHY3RTBkK3h5TjZIZWlJS1JaQgptWHp4eGpYL1RScWJQTHhkQ3RYcjA1ckdEREFkV2pBNjlna0g1eWU4UUtrVDZTQlErOGxscStwMjE2Z2lrdDBBCjJ4bmRMNllkaVZoY0tSYk9yNG5kOHhlc21lMDZ6YWRxSGFGWDI0SlR5bUx4R3ZYTlZ3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVWkZVdlRlUkJwTjhOOWlYOWQ2MDdRRE9FL3RZd0h3WURWUjBqQkJnd0ZvQVVaRlV2VGVSQgpwTjhOOWlYOWQ2MDdRRE9FL3RZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFzbjlXeTBibDdndmZUYnllT3UvTGdRZm0wSE5GZ2xUM3YvLzRKcG1TclI1SVdianFGMk1HZnFNNkVYRUEKdTJQcGkyRGFvUmUwd29vcVJrcGxNenpqK01Fd0JCOGtXTk13ZE5FQUNoOW16QmdvWkNCaXVJeVR3dVNWTWJPbwpQbHRmbnBBSTloZis4RWUyU0w2dWk4Rk0vSlI1YXg3d2V5cGdIeTdOdWxLcG5SVGRvU2VUNWRoNkdlTHEvZjdzCkZ4aUtBVUt6SkNIK0JzVjEyaXlUTnNMa0xvV3hOQmFKZUF6emtZbHNVK21ka0Q2cWRMTlFvRkF2ZXJjOGhadFgKSGg4aVB3TGFzbWR4OExsVVREbWRKdmpkalZnNWVhRHk4Y045MjM4dU55UGEycHVmS1R5OE5DOTZ2K3QvY0RDYQozaExYTXRCd09Kc254d21nbUdlUGRJNmFYZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]