apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVRGpSalJ2aWFHZDcxODFFWjhaTUkxYVhlUUpzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXpNRFV4T0RFd016SXpORm9YRFRJek1EWXhOekV3TXpJek5Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXJJT3RwTXJjcXJpN1BBMHp3OU91U09kNzF2MzlFMGIwaTluSgpUSWFKcnNEYzNMd1B5citnU0xxOXlBUFZzdUJGTG5WVmhMcWFMVXRhY0JQTDF0WVFzVnRYSnhjMFZwQ2x6Q1R0CjdCMnhRY3JqSk1JdVlvNnZqV2FjakFjMkhjc2pXcW9Dc0J1LzNaZXkvWS81Z0lUeW1SV25DRTA2YXQyd1NNK24KTlZtQ1BrRElpVXJqTitwV0lWaGlpbTY2Ui92dzhjSkpCYmVxSm9DMUY4YlJYWW5uaE1DL0syN3liK1RJUHdhSApjZ1NyajMwT29Ldko2YTJpeGdrV0lYaTdLcWFvdmZ6cXdpSmRwYmc5bW5ZSmxCcHFNQkdYdDR6cmZ0a3FLTmtnCjNPRFRtanNSTUJ2OFFCWDk4akdBMUI5blFFbCtPZCtuc1JZTDVhd0dLdWpGQml4WXNRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVQzJZOVE3YTI3d1R6RkNMYURIVkowWmwzOWZ3d0h3WURWUjBqQkJnd0ZvQVVDMlk5UTdhMgo3d1R6RkNMYURIVkowWmwzOWZ3d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFaaE5aOUsxMzR6QnJaSjVwS3ZMUnhjcjd4WXBxNG5DTXcxYmtPM3BxSnI5NmZnd3A5YVZZT2p2blZMcnEKRzY4TFZhOEdxVTRQSS9FM01UTWZiVE5ueTZZQnlaWm5IQzlaWHlXSFJzODgrajlzZmpwVzNEVXV6U3BNM2F5Ugo2dVVhQ21ybDRFa1F3R3dqSzVuUmJhUWd6cE1HUDZWTW95WXV0VzhyVEdSOVowK1Q3c2pvSmJSMy9QR0lqQUxjCnFROWNKTGE3TEZscDk0aHpCNzN0Vlhtc3ZzbVpKaXFzczJ2dVdhdDAvbTE2blM2Q1RCQk5VNmdLU1V2Z2xXS24KcDZ0ZTRBYWgxSmNNRlo3MXNRRFVJV0h3bjkzazVqUC9OU0tXeFV0OUhsY3BOUWYvYWlrc1N2TUMxUTg2NmE2cwpRKzFKdWhJNk10QWM4RmFteVlwUmlvUmRUUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]