apiVersion: v1
kind: Pod
metadata:
  name: pod-warning
  labels:
    app: pod-warning
spec:
  restartPolicy: OnFailure
  securityContext:
    runAsNonRoot: false
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo I am running as user $(id -u)"]
